{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NoFieldSelectors #-}

-- | Public surface for card definitions and the @allCards@ registry.
-- 'SomeCardDef', 'Card', their JSON/Show instances and the
-- 'HasRaces SomeCardDef' instance are defined here so the existing
-- 'Invasion.Card.hs-boot' stays valid; the DSL surface
-- (CardBuilder, EffectM, triggers, action builders, etc.) is
-- re-exported from the submodules listed below.
module Invasion.Card
  ( module Invasion.Card.Effects,
    module Invasion.Card.Builder,
    module Invasion.Card.Triggers,
    module Invasion.Card.Types,
    hasRace,
    allCards,
  )
where

import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import Invasion.Card.Builder
import Invasion.Card.Defs.Chaos
import Invasion.Card.Defs.DarkElf
import Invasion.Card.Defs.Dwarf
import Invasion.Card.Defs.Empire
import Invasion.Card.Defs.HighElf
import Invasion.Card.Defs.Neutral
import Invasion.Card.Defs.Orc
import Invasion.Card.Effects
import Invasion.Card.Triggers
import Invasion.Card.Types
import Invasion.Prelude
import Invasion.Types

-- | True iff the named card carries the given race. Looks the card up
-- in 'allCards'; returns 'False' if the code is unknown (defensive —
-- should never happen for in-play card codes).
hasRace :: Race -> CardCode -> Bool
hasRace r code = case Map.lookup code allCards of
  Just sd -> sd `isRace` r
  Nothing -> False

-- | The registry of every card the engine knows about, keyed by its
-- printed product code (e.g. @core-014@). Mirrors @cards.json@; the
-- two must stay in sync. Covers the core set, the full Corruption
-- cycle, and assorted later-cycle Chaos cards.
allCards :: Map CardCode SomeCardDef
allCards =
  Map.fromList
    -- Dwarf — core-001..025
    [ ("core-001", UnitCardDef defenderOfTheHold),
      ("core-002", UnitCardDef zhufbarEngineers),
      ("core-003", UnitCardDef hammererOfKarakAzul),
      ("core-004", UnitCardDef trollSlayers),
      ("core-005", UnitCardDef runesmith),
      ("core-006", UnitCardDef durgnarTheBold),
      ("core-007", UnitCardDef kingKazador),
      ("core-008", UnitCardDef dwarfCannonCrew),
      ("core-009", UnitCardDef dwarfMasons),
      ("core-010", UnitCardDef dwarfRanger),
      ("core-011", UnitCardDef mountainBrigade),
      ("core-012", UnitCardDef ironbreakersOfAnkhor),
      ("core-013", SupportCardDef runeOfFortitude),
      ("core-014", SupportCardDef keystoneForge),
      ("core-015", SupportCardDef organGun),
      ("core-016", SupportCardDef masterRuneOfDismay),
      ("core-017", QuestCardDef aGloriousDeath),
      ("core-018", SupportCardDef grudgeThrower),
      ("core-019", TacticCardDef buryingTheGrudge),
      ("core-020", TacticCardDef stubbornRefusal),
      ("core-021", TacticCardDef strikingTheGrudge),
      ("core-022", TacticCardDef grudgeThrowerAssault),
      ("core-023", TacticCardDef demolition),
      ("core-024", TacticCardDef wakeTheMountain),
      ("core-025", TacticCardDef masterRuneOfValaya),
      -- Empire — core-026..050
      ("core-026", UnitCardDef peasantMilitia),
      ("core-027", UnitCardDef reiksguardKnights),
      ("core-028", UnitCardDef brightWizardApprentice),
      ("core-029", UnitCardDef nulnTinkerers),
      ("core-030", UnitCardDef theGreatswords),
      ("core-031", UnitCardDef sigmarsBlessed),
      ("core-032", UnitCardDef thyrusGorman),
      ("core-033", UnitCardDef huntsmen),
      ("core-034", UnitCardDef warriorPriests),
      ("core-035", UnitCardDef freeCompany),
      ("core-036", UnitCardDef pistoliers),
      ("core-037", UnitCardDef johannesBroheim),
      ("core-038", SupportCardDef knightTraining),
      ("core-039", SupportCardDef churchOfSigmar),
      ("core-040", SupportCardDef cityGates),
      ("core-041", SupportCardDef shrineToTaal),
      ("core-042", SupportCardDef templeOfShallya),
      ("core-043", QuestCardDef defendTheBorder),
      ("core-044", TacticCardDef willOfTheElectors),
      ("core-045", TacticCardDef twinTailedComet),
      ("core-046", TacticCardDef demoralise),
      ("core-047", TacticCardDef franzsDecree),
      ("core-048", TacticCardDef forcedMarch),
      ("core-049", TacticCardDef judgementOfVerena),
      ("core-050", TacticCardDef sigmarsIntervention),
      -- High Elf — core-051..055 (only 5 in core)
      ("core-051", UnitCardDef silverHelmBrigade),
      ("core-052", UnitCardDef archmageOfSaphery),
      ("core-053", SupportCardDef blessingOfIsha),
      ("core-054", TacticCardDef radiantGaze),
      ("core-055", TacticCardDef greaterHeal),
      -- Orc — core-056..080
      ("core-056", UnitCardDef crookedTeefGoblins),
      ("core-057", UnitCardDef squigHerders),
      ("core-058", UnitCardDef ironclawsHorde),
      ("core-059", UnitCardDef followersOfMork),
      ("core-060", UnitCardDef blackOrcSquad),
      ("core-061", UnitCardDef boarBoyz),
      ("core-062", UnitCardDef urguck),
      ("core-063", UnitCardDef grimgorIronhide),
      ("core-064", UnitCardDef nightGoblins),
      ("core-065", UnitCardDef doomDivers),
      ("core-066", UnitCardDef lobberCrew),
      ("core-067", UnitCardDef bigUns),
      ("core-068", SupportCardDef rockLobber),
      ("core-069", SupportCardDef choppa),
      ("core-070", SupportCardDef totemOfGork),
      ("core-071", SupportCardDef bannaOfDaRedSunz),
      ("core-072", QuestCardDef smashEmAll),
      ("core-073", SupportCardDef grimgorsCamp),
      ("core-074", TacticCardDef smashGoBoom),
      ("core-075", TacticCardDef ripDereEadsOff),
      ("core-076", TacticCardDef wezBigga),
      ("core-077", TacticCardDef favourOfMork),
      ("core-078", TacticCardDef pillage),
      ("core-079", TacticCardDef waaagh),
      ("core-080", TacticCardDef trollVomit),
      -- Chaos — core-081..105
      ("core-081", UnitCardDef servantsOfKhorne),
      ("core-082", UnitCardDef savageMarauders),
      ("core-083", UnitCardDef festeringNurglings),
      ("core-084", UnitCardDef nurgleSorcerer),
      ("core-085", UnitCardDef chaosKnights),
      ("core-086", UnitCardDef cultistOfSlaanesh),
      ("core-087", UnitCardDef valkiaTheBloody),
      ("core-088", UnitCardDef melekhTheChanger),
      ("core-089", UnitCardDef fledglingChaosSpawn),
      ("core-090", UnitCardDef savageGors),
      ("core-091", UnitCardDef darkZealot),
      ("core-092", UnitCardDef bloodthirster),
      ("core-093", SupportCardDef cloudOfFlies),
      ("core-094", SupportCardDef horrificMutation),
      ("core-095", SupportCardDef sadisticMutation),
      ("core-096", SupportCardDef warpstoneMeteor),
      ("core-097", QuestCardDef journeyToTheGate),
      ("core-098", SupportCardDef shrineToNurgle),
      ("core-099", TacticCardDef seducedByDarkness),
      ("core-100", TacticCardDef willOfTzeentch),
      ("core-101", TacticCardDef nurglesPestilence),
      ("core-102", TacticCardDef flamesOfTzeentch),
      ("core-103", TacticCardDef bloodForTheBloodGod),
      ("core-104", TacticCardDef cullingTheWeak),
      ("core-105", TacticCardDef slaaneshsDomination),
      -- Dark Elf — core-106..110 (only 5 in core)
      ("core-106", UnitCardDef discipleOfKhaine),
      ("core-107", UnitCardDef vileSorceress),
      ("core-108", UnitCardDef coldOneRiders),
      ("core-109", SupportCardDef cauldronOfBlood),
      ("core-110", TacticCardDef hate),
      -- Neutral — core-111..127 (no core-119)
      ("core-111", SupportCardDef contestedVillage),
      ("core-112", SupportCardDef contestedFortress),
      ("core-113", SupportCardDef contestedStronghold),
      ("core-114", SupportCardDef armoury),
      ("core-115", SupportCardDef forgottenCemetery),
      ("core-116", SupportCardDef warpstoneExcavation),
      ("core-117", TacticCardDef pilgrimage),
      ("core-118", TacticCardDef burnItDown),
      ("core-120", QuestCardDef infiltrate),
      ("core-121", QuestCardDef prepareForWar),
      ("core-122", SupportCardDef allianceDwarfEmpire),
      ("core-123", SupportCardDef allianceEmpireHighElf),
      ("core-124", SupportCardDef allianceDwarfHighElf),
      ("core-125", SupportCardDef allianceChaosOrc),
      ("core-126", SupportCardDef allianceChaosDarkElf),
      ("core-127", SupportCardDef allianceOrcDarkElf),
      -- The Corruption cycle — The Skavenblight Threat (001-020)
      ("the-skavenblight-threat-001", UnitCardDef gurnisElite),
      ("the-skavenblight-threat-002", TacticCardDef standYourGround),
      ("the-skavenblight-threat-003", UnitCardDef nordlandHalberdiers),
      ("the-skavenblight-threat-004", TacticCardDef infiltrateTactic),
      ("the-skavenblight-threat-005", UnitCardDef tyriel),
      ("the-skavenblight-threat-006", TacticCardDef steelsBane),
      ("the-skavenblight-threat-007", QuestCardDef repairTheWaystones),
      ("the-skavenblight-threat-008", UnitCardDef spiderRiders),
      ("the-skavenblight-threat-009", SupportCardDef warPaint),
      ("the-skavenblight-threat-010", UnitCardDef chosenOfTzeentch),
      ("the-skavenblight-threat-011", TacticCardDef boltOfChange),
      ("the-skavenblight-threat-012", UnitCardDef malusDarkblade),
      ("the-skavenblight-threat-013", UnitCardDef morathisPegasus),
      ("the-skavenblight-threat-014", TacticCardDef weNeedYourBlood),
      ("the-skavenblight-threat-015", UnitCardDef greyseerThanquol),
      ("the-skavenblight-threat-016", UnitCardDef clanRats),
      ("the-skavenblight-threat-017", SupportCardDef warpLightningCannon),
      ("the-skavenblight-threat-018", UnitCardDef mariusTheRighteous),
      ("the-skavenblight-threat-019", SupportCardDef abandonedMine),
      ("the-skavenblight-threat-020", SupportCardDef forge),
      -- The Corruption cycle — Path of the Zealot (021-040)
      ("path-of-the-zealot-021", UnitCardDef dwarfMiner),
      ("path-of-the-zealot-022", SupportCardDef gromrilArmour),
      ("path-of-the-zealot-023", UnitCardDef gustavTheBear),
      ("path-of-the-zealot-024", UnitCardDef talabheimDetachment),
      ("path-of-the-zealot-025", SupportCardDef gateOfSigmar),
      ("path-of-the-zealot-026", TacticCardDef vaulsUnmaking),
      ("path-of-the-zealot-027", SupportCardDef repeaterBoltThrower),
      ("path-of-the-zealot-028", UnitCardDef arrerBoyz),
      ("path-of-the-zealot-029", TacticCardDef wolfRiderAssault),
      ("path-of-the-zealot-030", UnitCardDef buleLordOfPus),
      ("path-of-the-zealot-031", UnitCardDef bloodsworn),
      ("path-of-the-zealot-032", QuestCardDef wolvesOfTheNorth),
      ("path-of-the-zealot-033", UnitCardDef darkRiders),
      ("path-of-the-zealot-034", TacticCardDef callTheBlood),
      ("path-of-the-zealot-035", UnitCardDef poisonWindGlobadiers),
      ("path-of-the-zealot-036", TacticCardDef chitteringHorde),
      ("path-of-the-zealot-037", UnitCardDef zealotHunter),
      ("path-of-the-zealot-038", UnitCardDef veteranSellswords),
      ("path-of-the-zealot-039", TacticCardDef surpriseAssault),
      ("path-of-the-zealot-040", TacticCardDef animosity),
      -- The Corruption cycle — Tooth and Claw (041-060)
      ("tooth-and-claw-041", UnitCardDef gurniThorgrimson),
      ("tooth-and-claw-042", SupportCardDef anvilOfDoom),
      ("tooth-and-claw-043", TacticCardDef blessingOfValaya),
      ("tooth-and-claw-044", UnitCardDef reiksguardSwordsmen),
      ("tooth-and-claw-045", TacticCardDef ironDiscipline),
      ("tooth-and-claw-046", UnitCardDef dragonmage),
      ("tooth-and-claw-047", TacticCardDef giftsOfAenarion),
      ("tooth-and-claw-048", UnitCardDef ugrokBeardburna),
      ("tooth-and-claw-049", TacticCardDef mobUp),
      ("tooth-and-claw-050", QuestCardDef datsMine),
      ("tooth-and-claw-051", UnitCardDef blueHorrors),
      ("tooth-and-claw-052", TacticCardDef brutalOffering),
      ("tooth-and-claw-053", UnitCardDef coldOneChariot),
      ("tooth-and-claw-054", TacticCardDef graspingDarkness),
      ("tooth-and-claw-055", UnitCardDef ratOgres),
      ("tooth-and-claw-056", UnitCardDef gutterRunners),
      ("tooth-and-claw-057", UnitCardDef clanMouldersElite),
      ("tooth-and-claw-058", UnitCardDef errantWolf),
      ("tooth-and-claw-059", TacticCardDef reapWhatsSown),
      ("tooth-and-claw-060", SupportCardDef scoutCamp),
      -- The Corruption cycle — The Deathmaster's Dance (061-080)
      ("the-deathmaster-s-dance-061", UnitCardDef mountainLegion),
      ("the-deathmaster-s-dance-062", TacticCardDef emptyTheHold),
      ("the-deathmaster-s-dance-063", QuestCardDef reclaimTheHold),
      ("the-deathmaster-s-dance-064", UnitCardDef vigilantElector),
      ("the-deathmaster-s-dance-065", UnitCardDef flagellants),
      ("the-deathmaster-s-dance-066", TacticCardDef ulricsFury),
      ("the-deathmaster-s-dance-067", UnitCardDef silverHelmDetachment),
      ("the-deathmaster-s-dance-068", SupportCardDef ishasGaze),
      ("the-deathmaster-s-dance-069", TacticCardDef banish),
      ("the-deathmaster-s-dance-070", UnitCardDef ironBoyz),
      ("the-deathmaster-s-dance-071", SupportCardDef grimgorsSpike),
      ("the-deathmaster-s-dance-072", TacticCardDef swarmEm),
      ("the-deathmaster-s-dance-073", UnitCardDef greatUncleanOne),
      ("the-deathmaster-s-dance-074", SupportCardDef hellcannonReserves),
      ("the-deathmaster-s-dance-075", TacticCardDef offeringOfBlood),
      ("the-deathmaster-s-dance-076", UnitCardDef warHydra),
      ("the-deathmaster-s-dance-077", SupportCardDef reaperBoltThrower),
      ("the-deathmaster-s-dance-078", TacticCardDef caughtTheScent),
      ("the-deathmaster-s-dance-079", UnitCardDef deathmasterSniktch),
      ("the-deathmaster-s-dance-080", UnitCardDef juvenileWyvern),
      -- The Corruption cycle — The Warpstone Chronicles (081-100)
      ("the-warpstone-chronicles-081", UnitCardDef dragonslayer),
      ("the-warpstone-chronicles-082", SupportCardDef greatBookOfGrudges),
      ("the-warpstone-chronicles-083", SupportCardDef flameCannon),
      ("the-warpstone-chronicles-084", UnitCardDef vigilantPistoliers),
      ("the-warpstone-chronicles-085", SupportCardDef runefangOfSolland),
      ("the-warpstone-chronicles-086", SupportCardDef helblasterVolleyGun),
      ("the-warpstone-chronicles-087", UnitCardDef finreirsGuard),
      ("the-warpstone-chronicles-088", SupportCardDef warCrownOfSaphery),
      ("the-warpstone-chronicles-089", TacticCardDef secondSight),
      ("the-warpstone-chronicles-090", UnitCardDef snotlingPumpWagon),
      ("the-warpstone-chronicles-091", SupportCardDef bashasBloodaxe),
      ("the-warpstone-chronicles-092", SupportCardDef thickSkinned),
      ("the-warpstone-chronicles-093", UnitCardDef alluringDaemonettes),
      ("the-warpstone-chronicles-094", TacticCardDef berserkFury),
      ("the-warpstone-chronicles-095", SupportCardDef daemonsword),
      ("the-warpstone-chronicles-096", UnitCardDef naggarothSpearmen),
      ("the-warpstone-chronicles-097", SupportCardDef hydraBlade),
      ("the-warpstone-chronicles-098", QuestCardDef slaverRaid),
      ("the-warpstone-chronicles-099", SupportCardDef ancientWaystone),
      ("the-warpstone-chronicles-100", SupportCardDef fellblade),
      -- The Corruption cycle — Arcane Fire (101-120)
      ("arcane-fire-101", UnitCardDef longbeards),
      ("arcane-fire-102", TacticCardDef runeOfHearthAndHome),
      ("arcane-fire-103", TacticCardDef hewnFromTheMountain),
      ("arcane-fire-104", UnitCardDef helblasterCrew),
      ("arcane-fire-105", TacticCardDef sigmarsBrilliance),
      ("arcane-fire-106", QuestCardDef protectTheEmpire),
      ("arcane-fire-107", UnitCardDef ellyrianReavers),
      ("arcane-fire-108", TacticCardDef morvaelsLegacy),
      ("arcane-fire-109", TacticCardDef chargeOfTheSilverHelms),
      ("arcane-fire-110", UnitCardDef snotlingSaboteurs),
      ("arcane-fire-111", TacticCardDef daBrainbusta),
      ("arcane-fire-112", TacticCardDef easyPickins),
      ("arcane-fire-113", UnitCardDef beastOfChaos),
      ("arcane-fire-114", TacticCardDef cacophonicScream),
      ("arcane-fire-115", TacticCardDef blessingsOfTzeentch),
      ("arcane-fire-116", UnitCardDef slaveDriver),
      ("arcane-fire-117", TacticCardDef yourWillIsMine),
      ("arcane-fire-118", SupportCardDef witchHagsCurse),
      ("arcane-fire-119", SupportCardDef greyseersLair),
      ("arcane-fire-120", UnitCardDef plagueMonk),
      -- Assault on Ulthuan (deluxe expansion)
      ("assault-on-ulthuan-001", UnitCardDef envoyFromAverlorn),
      ("assault-on-ulthuan-002", UnitCardDef shadowWarrior),
      ("assault-on-ulthuan-003", UnitCardDef swordMastersOfHoeth),
      ("assault-on-ulthuan-004", UnitCardDef highElfSpearmen),
      ("assault-on-ulthuan-005", UnitCardDef caradryan),
      ("assault-on-ulthuan-006", UnitCardDef initiateOfSaphery),
      ("assault-on-ulthuan-007", UnitCardDef loremasterOfHoeth),
      ("assault-on-ulthuan-008", UnitCardDef illyriel),
      ("assault-on-ulthuan-009", UnitCardDef dragonPrince),
      ("assault-on-ulthuan-011", QuestCardDef defendTorAendris),
      ("assault-on-ulthuan-012", SupportCardDef dragonMageWakening),
      ("assault-on-ulthuan-013", SupportCardDef theGlitteringTower),
      ("assault-on-ulthuan-014", SupportCardDef shrineOfAsuryan),
      ("assault-on-ulthuan-015", SupportCardDef templeOfVaul),
      ("assault-on-ulthuan-016", TacticCardDef tearOfIsha),
      ("assault-on-ulthuan-017", TacticCardDef flamesOfThePhoenix),
      ("assault-on-ulthuan-020", TacticCardDef giftOfLife),
      ("assault-on-ulthuan-022", UnitCardDef darkInitiate),
      ("assault-on-ulthuan-023", UnitCardDef walkingSacrifice),
      ("assault-on-ulthuan-025", UnitCardDef shades),
      ("assault-on-ulthuan-026", UnitCardDef coldOneKnight),
      ("assault-on-ulthuan-028", UnitCardDef darkSorceress),
      ("assault-on-ulthuan-029", UnitCardDef corsairsOfGhrond),
      ("assault-on-ulthuan-030", UnitCardDef lokhirFellheart),
      ("assault-on-ulthuan-031", QuestCardDef nightRaids),
      ("assault-on-ulthuan-032", QuestCardDef sackTorAendris),
      ("assault-on-ulthuan-033", SupportCardDef mindKiller),
      ("assault-on-ulthuan-034", SupportCardDef wordOfPain),
      ("assault-on-ulthuan-035", SupportCardDef harGaneth),
      ("assault-on-ulthuan-037", TacticCardDef lashThePrisoner),
      ("assault-on-ulthuan-038", TacticCardDef darkVisions),
      ("assault-on-ulthuan-039", TacticCardDef chillwind),
      ("assault-on-ulthuan-040", TacticCardDef batheInBlood),
      ("assault-on-ulthuan-042", TacticCardDef invokeKhainesWrath),
      ("assault-on-ulthuan-043", UnitCardDef slayersOfKarakKadrin),
      ("assault-on-ulthuan-044", SupportCardDef mountainBarracks),
      ("assault-on-ulthuan-045", TacticCardDef lureThemOut),
      ("assault-on-ulthuan-046", UnitCardDef goldWizardAcolyte),
      ("assault-on-ulthuan-047", SupportCardDef battleStandard),
      ("assault-on-ulthuan-048", TacticCardDef surrender),
      ("assault-on-ulthuan-049", UnitCardDef wyvernRider),
      ("assault-on-ulthuan-050", SupportCardDef scrapHeap),
      ("assault-on-ulthuan-051", TacticCardDef footOfGork),
      ("assault-on-ulthuan-052", UnitCardDef maledictorOfTzeentch),
      ("assault-on-ulthuan-053", SupportCardDef bloodFrenzy),
      ("assault-on-ulthuan-054", TacticCardDef tzeentchsFirestorm),
      ("assault-on-ulthuan-055", SupportCardDef treasureVaults),
      ("assault-on-ulthuan-056", TacticCardDef ancientMap),
      ("assault-on-ulthuan-057", TacticCardDef innovation),
      -- The Enemy cycle — Bleeding Sun (101-120)
      ("bleeding-sun-102", TacticCardDef honorInDeath),
      ("bleeding-sun-104", UnitCardDef stonebearer),
      ("bleeding-sun-107", TacticCardDef blessingOfMyrmidia),
      ("bleeding-sun-108", SupportCardDef moonStaffOfLileath),
      ("bleeding-sun-109", SupportCardDef dragonArmour),
      ("bleeding-sun-110", UnitCardDef madShaman),
      ("bleeding-sun-111", UnitCardDef giantSpider),
      ("bleeding-sun-113", TacticCardDef smashDerBeards),
      ("bleeding-sun-114", UnitCardDef beastOfRot),
      ("bleeding-sun-115", SupportCardDef necroticSpasms),
      ("bleeding-sun-117", SupportCardDef soulStealer),
      ("bleeding-sun-118", UnitCardDef grailKnight),
      ("bleeding-sun-119", SupportCardDef advancedEngineering),
      -- The Enemy cycle — The Burning of Derricksburg (001-020)
      ("the-burning-of-derricksburg-001", UnitCardDef bodyguardOfBelegar),
      ("the-burning-of-derricksburg-002", SupportCardDef miningTunnels),
      ("the-burning-of-derricksburg-005", SupportCardDef derricksburgForge),
      ("the-burning-of-derricksburg-006", SupportCardDef griffonStandard),
      ("the-burning-of-derricksburg-008", TacticCardDef doYouKnowWhoIAm),
      ("the-burning-of-derricksburg-011", UnitCardDef schemingCultist),
      ("the-burning-of-derricksburg-013", UnitCardDef wingedFury),
      ("the-burning-of-derricksburg-014", TacticCardDef spreadingDarkness),
      ("the-burning-of-derricksburg-016", UnitCardDef druchiiNoble),
      ("the-burning-of-derricksburg-017", TacticCardDef whipTheSlaves),
      ("the-burning-of-derricksburg-019", TacticCardDef entropy),
      -- The Enemy cycle — The Fall of Karak Grimaz (021-040)
      ("the-fall-of-karak-grimaz-021", TacticCardDef masterRuneOfSpite),
      ("the-fall-of-karak-grimaz-022", UnitCardDef runesmithApprentice),
      ("the-fall-of-karak-grimaz-023", SupportCardDef ancestralTomb),
      ("the-fall-of-karak-grimaz-024", UnitCardDef grudgebearer),
      ("the-fall-of-karak-grimaz-026", TacticCardDef calledBack),
      ("the-fall-of-karak-grimaz-027", TacticCardDef scrollOfAsur),
      ("the-fall-of-karak-grimaz-029", UnitCardDef followersOfSkarsnik),
      ("the-fall-of-karak-grimaz-030", UnitCardDef stuntySmasha),
      ("the-fall-of-karak-grimaz-033", QuestCardDef smashEmBashEm),
      ("the-fall-of-karak-grimaz-035", TacticCardDef grandfathersCall),
      ("the-fall-of-karak-grimaz-036", UnitCardDef vanguardOfWoe),
      ("the-fall-of-karak-grimaz-038", SupportCardDef bottomlessMine),
      ("the-fall-of-karak-grimaz-039", SupportCardDef darkAbyss),
      ("the-fall-of-karak-grimaz-040", TacticCardDef longWinter),
      -- The Enemy cycle — The Silent Forge (041-060)
      ("the-silent-forge-041", UnitCardDef sonOfGrungi),
      ("the-silent-forge-043", UnitCardDef blackKnightsOfMorr),
      ("the-silent-forge-046", UnitCardDef descendantOfIndraugnir),
      ("the-silent-forge-050", UnitCardDef fungusbrewGoblin),
      ("the-silent-forge-052", UnitCardDef eslian),
      ("the-silent-forge-053", TacticCardDef embersToInferno),
      ("the-silent-forge-054", UnitCardDef dwarfSlaves),
      ("the-silent-forge-055", UnitCardDef blackGuardAspirant),
      ("the-silent-forge-056", SupportCardDef standardOfClarKarond),
      ("the-silent-forge-058", UnitCardDef battlePilgrims),
      ("the-silent-forge-060", TacticCardDef muck),
      -- The Enemy cycle — The Fourth Waystone (081-100)
      ("the-fourth-waystone-083", UnitCardDef brightWizardAcolyte),
      ("the-fourth-waystone-084", TacticCardDef douseTheFlames),
      ("the-fourth-waystone-086", UnitCardDef spearhostOfAsuryan),
      ("the-fourth-waystone-089", UnitCardDef highMountainTroll),
      ("the-fourth-waystone-090", TacticCardDef disStuffBurnsGud),
      ("the-fourth-waystone-091", UnitCardDef viciousMarauder),
      ("the-fourth-waystone-092", SupportCardDef taintedWell),
      ("the-fourth-waystone-093", TacticCardDef bloodburnPoison),
      ("the-fourth-waystone-095", SupportCardDef barbedWhip),
      ("the-fourth-waystone-100", UnitCardDef mountainBrigands),
      -- The Enemy cycle — Redemption of a Mage (061-080)
      ("redemption-of-a-mage-061", UnitCardDef grombrindalsElite),
      ("redemption-of-a-mage-065", SupportCardDef higherGround),
      ("redemption-of-a-mage-068", UnitCardDef dreamerOfDragons),
      ("redemption-of-a-mage-069", TacticCardDef courageOfAenarion),
      ("redemption-of-a-mage-070", UnitCardDef githitFroatcutta),
      ("redemption-of-a-mage-071", SupportCardDef tooArdToDie),
      ("redemption-of-a-mage-072", UnitCardDef heraldOfChange),
      ("redemption-of-a-mage-073", UnitCardDef disgracedChampion),
      ("redemption-of-a-mage-078", SupportCardDef ancientAlliance),
      ("redemption-of-a-mage-079", SupportCardDef evilAlliance),
      -- March of the Damned (deluxe expansion)
      ("march-of-the-damned-001", UnitCardDef serpentSlayer),
      ("march-of-the-damned-002", UnitCardDef longDrongsPirates),
      ("march-of-the-damned-003", SupportCardDef oathstone),
      ("march-of-the-damned-004", TacticCardDef toughAsNails),
      ("march-of-the-damned-005", TacticCardDef mercilessAssault),
      ("march-of-the-damned-006", UnitCardDef jadeAcolyte),
      ("march-of-the-damned-007", UnitCardDef rodriksRaiders),
      ("march-of-the-damned-008", SupportCardDef warMachineEmplacement),
      ("march-of-the-damned-009", SupportCardDef gardenOfMorr),
      ("march-of-the-damned-010", TacticCardDef manaanTakeYou),
      ("march-of-the-damned-011", UnitCardDef seaGuardCaptain),
      ("march-of-the-damned-012", UnitCardDef keeperOfTheFlame),
      ("march-of-the-damned-013", SupportCardDef citadelOfDusk),
      ("march-of-the-damned-014", SupportCardDef elvenWarship),
      ("march-of-the-damned-015", TacticCardDef fromBeneathTheWaves),
      ("march-of-the-damned-016", UnitCardDef savageBoyz),
      ("march-of-the-damned-017", UnitCardDef forestGoblins),
      ("march-of-the-damned-018", SupportCardDef trollDen),
      ("march-of-the-damned-019", TacticCardDef spidaHuntin),
      ("march-of-the-damned-020", TacticCardDef yousBigga),
      ("march-of-the-damned-021", UnitCardDef lordOfChange),
      ("march-of-the-damned-022", UnitCardDef brayShaman),
      ("march-of-the-damned-023", SupportCardDef bloodboilFever),
      ("march-of-the-damned-024", TacticCardDef cloyingQuagmire),
      ("march-of-the-damned-025", TacticCardDef bloodSummoning),
      ("march-of-the-damned-026", UnitCardDef seasonedCorsair),
      ("march-of-the-damned-027", UnitCardDef blackDragonRider),
      ("march-of-the-damned-028", SupportCardDef corsairRaider),
      ("march-of-the-damned-029", SupportCardDef slavePen),
      ("march-of-the-damned-030", TacticCardDef aSlaveForEveryOccasion),
      ("march-of-the-damned-031", UnitCardDef skinksOfSotek),
      ("march-of-the-damned-032", UnitCardDef skinkSkirmishers),
      ("march-of-the-damned-033", UnitCardDef spawnOfItzl),
      ("march-of-the-damned-034", UnitCardDef saurusWarriors),
      ("march-of-the-damned-035", UnitCardDef templeGuard),
      ("march-of-the-damned-036", UnitCardDef carnosaurRider),
      ("march-of-the-damned-037", UnitCardDef loqtza),
      ("march-of-the-damned-038", TacticCardDef savageRush),
      ("march-of-the-damned-039", SupportCardDef bloodShrineOfSotek),
      ("march-of-the-damned-040", SupportCardDef cloakOfFeathers),
      ("march-of-the-damned-041", TacticCardDef bornPredators),
      ("march-of-the-damned-042", TacticCardDef blessedSpawning),
      ("march-of-the-damned-043", UnitCardDef cryptGhouls),
      ("march-of-the-damned-044", UnitCardDef skeletalHorde),
      ("march-of-the-damned-045", UnitCardDef drownedZombies),
      ("march-of-the-damned-046", UnitCardDef spiritHost),
      ("march-of-the-damned-047", UnitCardDef enragedVarghulf),
      ("march-of-the-damned-048", UnitCardDef wightLord),
      ("march-of-the-damned-049", UnitCardDef countessIseara),
      ("march-of-the-damned-050", SupportCardDef numberlessGraves),
      ("march-of-the-damned-051", SupportCardDef corpseCart),
      ("march-of-the-damned-052", SupportCardDef theScreamingBanner),
      ("march-of-the-damned-053", TacticCardDef raiseDead),
      ("march-of-the-damned-054", TacticCardDef beguile),
      ("march-of-the-damned-055", UnitCardDef jezzailTeam),
      -- Cataclysm (deluxe expansion)
      ("cataclysm-002", UnitCardDef hammersmith),
      ("cataclysm-006", SupportCardDef hallOfHeroes),
      ("cataclysm-009", UnitCardDef makkaGreenfist),
      ("cataclysm-013", SupportCardDef bigGuns),
      ("cataclysm-020", UnitCardDef ferventDisciple),
      ("cataclysm-021", SupportCardDef luminarkOfHysh),
      ("cataclysm-022", SupportCardDef garrisoned),
      ("cataclysm-025", UnitCardDef lirdir),
      ("cataclysm-028", UnitCardDef arcanePurifier),
      ("cataclysm-033", UnitCardDef lordOfKhorne),
      ("cataclysm-034", UnitCardDef bloodcrusher),
      ("cataclysm-037", SupportCardDef riftOfChaos),
      ("cataclysm-042", UnitCardDef crimsonBrides),
      -- The Morrslieb cycle — The Chaos Moon (021-040)
      ("the-chaos-moon-022", UnitCardDef bugmansRangers),
      ("the-chaos-moon-023", SupportCardDef bugmansTankard),
      ("the-chaos-moon-025", SupportCardDef lootedUmieTown),
      ("the-chaos-moon-028", TacticCardDef chainLightning),
      ("the-chaos-moon-030", SupportCardDef dragonsLair),
      ("the-chaos-moon-031", QuestCardDef followThePortent),
      ("the-chaos-moon-032", UnitCardDef doombull),
      ("the-chaos-moon-036", UnitCardDef alluringChosen),
      ("the-chaos-moon-033", SupportCardDef desecratedTemple),
      ("the-chaos-moon-034", TacticCardDef plagueBomb),
      ("the-chaos-moon-035", UnitCardDef frenziedWitchElf),
      ("the-chaos-moon-037", TacticCardDef sacrificeToKhaine),
      ("the-chaos-moon-024", UnitCardDef nightGoblinFanatic),
      ("the-chaos-moon-040", UnitCardDef viciousClanrat),
      -- The Morrslieb cycle — The Eclipse of Hope (081-100)
      ("the-eclipse-of-hope-081", UnitCardDef mountainGuard),
      ("the-eclipse-of-hope-083", TacticCardDef craftingTheRune),
      ("the-eclipse-of-hope-084", UnitCardDef bigBoss),
      ("the-eclipse-of-hope-085", TacticCardDef firinDaSpell),
      ("the-eclipse-of-hope-086", UnitCardDef gloriousPreceptor),
      ("the-eclipse-of-hope-087", UnitCardDef osterknachtElite),
      ("the-eclipse-of-hope-089", UnitCardDef valorousMage),
      ("the-eclipse-of-hope-088", TacticCardDef masteringTheSpell),
      ("the-eclipse-of-hope-090", SupportCardDef starwoodStaff),
      ("the-eclipse-of-hope-091", TacticCardDef perfectingTheSpell),
      ("the-eclipse-of-hope-100", SupportCardDef asraiLongbow),
      ("the-eclipse-of-hope-093", SupportCardDef brandedByKhorne),
      ("the-eclipse-of-hope-094", TacticCardDef unleashingTheSpell),
      ("the-eclipse-of-hope-095", UnitCardDef toxicHydra),
      ("the-eclipse-of-hope-096", TacticCardDef testingTheSpell),
      ("the-eclipse-of-hope-097", QuestCardDef malekithsRage),
      ("the-eclipse-of-hope-098", UnitCardDef wardancer),
      ("the-eclipse-of-hope-099", UnitCardDef deadlySalamander),
      -- The Morrslieb cycle — Signs in the Stars (061-080)
      ("signs-in-the-stars-061", UnitCardDef beleaguredScout),
      ("signs-in-the-stars-062", SupportCardDef karakAzulForge),
      ("signs-in-the-stars-064", UnitCardDef sneakyGit),
      ("signs-in-the-stars-065", UnitCardDef squigHopper),
      ("signs-in-the-stars-068", UnitCardDef innerCircleKnight),
      ("signs-in-the-stars-069", TacticCardDef waitingInAmbush),
      ("signs-in-the-stars-070", UnitCardDef bladelord),
      ("signs-in-the-stars-071", TacticCardDef shieldOfSaphery),
      ("signs-in-the-stars-072", TacticCardDef cometOfCasandora),
      ("signs-in-the-stars-076", UnitCardDef enragedManticore),
      ("signs-in-the-stars-077", SupportCardDef witchbrew),
      ("signs-in-the-stars-078", UnitCardDef drycha),
      ("signs-in-the-stars-080", TacticCardDef danseMacabre),
      -- The Morrslieb cycle — The Twin-Tailed Comet (041-060)
      ("the-twin-tailed-comet-041", UnitCardDef daemonslayer),
      ("the-twin-tailed-comet-043", TacticCardDef theSlayerOath),
      ("the-twin-tailed-comet-044", UnitCardDef skarsnikAndGobbla),
      ("the-twin-tailed-comet-046", SupportCardDef tribalTattoos),
      ("the-twin-tailed-comet-047", UnitCardDef celestialWizard),
      ("the-twin-tailed-comet-054", QuestCardDef emptyingTheWastes),
      ("the-twin-tailed-comet-059", SupportCardDef forgottenCairn),
      ("the-twin-tailed-comet-048", SupportCardDef rallyPoint),
      ("the-twin-tailed-comet-050", UnitCardDef whiteLionVanguard),
      ("the-twin-tailed-comet-051", UnitCardDef trueMage),
      ("the-twin-tailed-comet-052", UnitCardDef centigor),
      ("the-twin-tailed-comet-053", UnitCardDef sorcererOfTzeentch),
      ("the-twin-tailed-comet-055", UnitCardDef bloodcallSorceress),
      ("the-twin-tailed-comet-057", SupportCardDef anointedCauldron),
      -- The Morrslieb cycle — Omens of Ruin (001-020)
      ("omens-of-ruin-001", UnitCardDef ancientLongbeards),
      ("omens-of-ruin-008", QuestCardDef visitTheHauntedCity),
      ("omens-of-ruin-003", UnitCardDef poisonousWyvern),
      ("omens-of-ruin-004", UnitCardDef riverTroll),
      ("omens-of-ruin-005", SupportCardDef boarPen),
      ("omens-of-ruin-006", UnitCardDef steamTank),
      ("omens-of-ruin-007", SupportCardDef hiddenGrove),
      ("omens-of-ruin-009", UnitCardDef korhil),
      ("omens-of-ruin-010", UnitCardDef tiranocChariot),
      ("omens-of-ruin-011", SupportCardDef eatineHarbour),
      ("omens-of-ruin-012", UnitCardDef ungorRaiders),
      ("omens-of-ruin-013", SupportCardDef markOfChaos),
      ("omens-of-ruin-015", UnitCardDef witchHag),
      ("omens-of-ruin-016", UnitCardDef darkElfInfiltrator),
      ("omens-of-ruin-017", SupportCardDef malekithsThrone),
      ("omens-of-ruin-019", UnitCardDef nimbleSpearman),
      ("omens-of-ruin-020", TacticCardDef bribery),
      -- The Morrslieb cycle — Portent of Doom (081-100)
      ("portent-of-doom-081", SupportCardDef eyeOfSheerian),
      ("portent-of-doom-082", LegendCardDef skarbrand),
      ("portent-of-doom-088", TacticCardDef theSealedVaults),
      -- The Morrslieb cycle — Fiery Dawn (101-120)
      ("fiery-dawn-105", TacticCardDef deyzBigga),
      ("fiery-dawn-106", TacticCardDef smashEm),
      ("fiery-dawn-107", UnitCardDef veteranGreatsword),
      ("fiery-dawn-109", SupportCardDef duelistTraining),
      ("fiery-dawn-112", TacticCardDef furyOfAenarion),
      ("fiery-dawn-103", QuestCardDef aidFromTheDepths),
      ("fiery-dawn-108", SupportCardDef helstormRocketBattery),
      ("fiery-dawn-114", TacticCardDef callTheBrayherd),
      ("fiery-dawn-116", TacticCardDef darkBlessing),
      ("fiery-dawn-117", TacticCardDef batheInTheCauldron),
      ("fiery-dawn-118", UnitCardDef forestDragon),
      ("fiery-dawn-119", SupportCardDef pureWarpstone),
      -- The Capital Cycle — The Inevitable City (001-020)
      ("the-inevitable-city-002", UnitCardDef squigTrackers),
      ("the-inevitable-city-003", UnitCardDef vanKlumpfsBuccaneers),
      ("the-inevitable-city-004", UnitCardDef princeOfCaledor),
      ("the-inevitable-city-005", UnitCardDef doomBearer),
      ("the-inevitable-city-007", UnitCardDef pinkHorror),
      ("the-inevitable-city-008", UnitCardDef savageForsaken),
      ("the-inevitable-city-010", UnitCardDef screamersOfTzeentch),
      ("the-inevitable-city-011", SupportCardDef theBleedingWall),
      ("the-inevitable-city-012", SupportCardDef wallOfMaggots),
      ("the-inevitable-city-013", SupportCardDef ironThroneroom),
      ("the-inevitable-city-014", TacticCardDef stormOfChange),
      ("the-inevitable-city-016", UnitCardDef warhawkRider),
      ("the-inevitable-city-015", UnitCardDef scionsOfMisery),
      ("the-inevitable-city-018", UnitCardDef mannfredVonCarstein),
      ("the-inevitable-city-019", TacticCardDef willpower),
      ("the-inevitable-city-020", QuestCardDef raidingCamps),
      -- The Capital Cycle — Realm of the Phoenix King (021-040)
      ("realm-of-the-phoenix-king-022", UnitCardDef mushroomHunters),
      ("realm-of-the-phoenix-king-023", SupportCardDef clockworkHorse),
      ("realm-of-the-phoenix-king-025", UnitCardDef seaLordAislinn),
      ("realm-of-the-phoenix-king-026", UnitCardDef whiteLionChampion),
      ("realm-of-the-phoenix-king-027", UnitCardDef heraldOfMoraiHeg),
      ("realm-of-the-phoenix-king-028", UnitCardDef starDragon),
      ("realm-of-the-phoenix-king-030", SupportCardDef straitsOfLothern),
      ("realm-of-the-phoenix-king-032", SupportCardDef eataineWarRoom),
      ("realm-of-the-phoenix-king-033", TacticCardDef inflame),
      ("realm-of-the-phoenix-king-034", SupportCardDef horrificFavour),
      ("realm-of-the-phoenix-king-035", UnitCardDef spawnOfKintearer),
      ("realm-of-the-phoenix-king-038", TacticCardDef forUsTheBellTolls),
      -- The Capital Cycle — The Iron Rock (041-060)
      ("the-iron-rock-041", UnitCardDef guildOfEngineers),
      ("the-iron-rock-042", UnitCardDef bannaThief),
      ("the-iron-rock-044", UnitCardDef squigLobber),
      ("the-iron-rock-045", UnitCardDef rugludsArmouredOrcs),
      ("the-iron-rock-043", UnitCardDef madtoofIronleg),
      ("the-iron-rock-046", UnitCardDef toofTrader),
      ("the-iron-rock-049", SupportCardDef bossPit),
      ("the-iron-rock-050", TacticCardDef snotlingAmbush),
      ("the-iron-rock-052", UnitCardDef sonsOfCoin),
      ("the-iron-rock-055", TacticCardDef countermoves),
      ("the-iron-rock-054", UnitCardDef beastmanShaman),
      ("the-iron-rock-058", UnitCardDef chakax),
      ("the-iron-rock-060", QuestCardDef raidingParties),
      -- The Capital Cycle — Karaz-a-Karak (061-080)
      ("karaz-a-karak-061", UnitCardDef mountainSentry),
      ("karaz-a-karak-062", UnitCardDef queenHelga),
      ("karaz-a-karak-064", UnitCardDef runeblades),
      ("karaz-a-karak-067", SupportCardDef heartForge),
      ("karaz-a-karak-069", SupportCardDef theGreatGuildHall),
      ("karaz-a-karak-070", TacticCardDef leaveNoTrace),
      ("karaz-a-karak-076", UnitCardDef zombieDragon),
      ("karaz-a-karak-079", TacticCardDef buildingPlans),
      ("karaz-a-karak-080", QuestCardDef buildingForWar),
      -- The Capital Cycle — City of Winter (081-100)
      ("city-of-winter-082", TacticCardDef fistsOfMork),
      ("city-of-winter-081", TacticCardDef burlocksIngenuity),
      ("city-of-winter-083", TacticCardDef pigeonBombs),
      ("city-of-winter-084", TacticCardDef convocationOfEagles),
      ("city-of-winter-085", TacticCardDef soporificMusk),
      ("city-of-winter-086", TacticCardDef barbedSnares),
      ("city-of-winter-087", UnitCardDef bannermanOfTheCrag),
      ("city-of-winter-089", UnitCardDef theEbonblades),
      ("city-of-winter-090", UnitCardDef anlecLookout),
      ("city-of-winter-091", UnitCardDef hagQueen),
      ("city-of-winter-093", SupportCardDef harpyAerie),
      ("city-of-winter-094", SupportCardDef courtOfTheWitchKing),
      ("city-of-winter-096", UnitCardDef kindredOfLaithKourn),
      ("city-of-winter-097", TacticCardDef pageantOfShrikes),
      ("city-of-winter-095", TacticCardDef callOfTheKraken),
      ("city-of-winter-100", QuestCardDef raidingShips),
      -- The Capital Cycle — The Imperial Throne (101-120)
      ("the-imperial-throne-102", UnitCardDef babySquig),
      ("the-imperial-throne-103", UnitCardDef imperialDrummer),
      ("the-imperial-throne-105", UnitCardDef devoteeOfChamon),
      ("the-imperial-throne-106", UnitCardDef priestsOfSigmar),
      ("the-imperial-throne-107", UnitCardDef stirlandDeathjacks),
      ("the-imperial-throne-108", UnitCardDef wingedRidersOfKislev),
      ("the-imperial-throne-109", SupportCardDef theImperialZoo),
      ("the-imperial-throne-111", SupportCardDef cathedralOfSigmar),
      ("the-imperial-throne-112", TacticCardDef doublingOfTheGuard),
      ("the-imperial-throne-114", UnitCardDef daemonPrince),
      ("the-imperial-throne-115", SupportCardDef sacrificialPyre),
      ("the-imperial-throne-117", TacticCardDef gazeOfNagash),
      ("the-imperial-throne-118", TacticCardDef aPromiseOfWar),
      ("the-imperial-throne-120", QuestCardDef recruitingForWar),
      -- Bloodquest cycle — Rising Dawn (pack 1)
      ("rising-dawn-001", SupportCardDef dawnstarSword),
      ("rising-dawn-003", SupportCardDef stoneVengeance),
      ("rising-dawn-004", TacticCardDef callingTheCouncil),
      ("rising-dawn-005", UnitCardDef orcBully),
      ("rising-dawn-007", UnitCardDef emperorsChosen),
      ("rising-dawn-008", TacticCardDef rageOfTheBear),
      ("rising-dawn-009", UnitCardDef lothernSeaMaster),
      ("rising-dawn-010", SupportCardDef gatheringTheWinds),
      ("rising-dawn-011", SupportCardDef helmOfFortune),
      ("rising-dawn-012", UnitCardDef mountedMarauders),
      ("rising-dawn-013", TacticCardDef boonOfTzeentch),
      ("rising-dawn-014", UnitCardDef maranith),
      ("rising-dawn-015", SupportCardDef towerOfOblivion),
      ("rising-dawn-016", UnitCardDef blessedEnchantress),
      ("rising-dawn-017", UnitCardDef hiddenSorceress),
      ("rising-dawn-018", QuestCardDef newTradeRoute),
      -- Bloodquest cycle — Fragments of Power (pack 2)
      ("fragments-of-power-021", SupportCardDef starCrownFragments),
      ("fragments-of-power-024", SupportCardDef bloodVengeance),
      ("fragments-of-power-022", LegendCardDef ungrimBaragor),
      ("fragments-of-power-023", UnitCardDef masterOfMaps),
      ("fragments-of-power-025", UnitCardDef arachnarokSpider),
      ("fragments-of-power-026", TacticCardDef daGreatLeader),
      ("fragments-of-power-027", UnitCardDef averheimSoldiers),
      ("fragments-of-power-028", SupportCardDef higherLearning),
      ("fragments-of-power-029", UnitCardDef ellyrianPatron),
      ("fragments-of-power-031", UnitCardDef swornOfKhorne),
      ("fragments-of-power-032", SupportCardDef stolenSkin),
      ("fragments-of-power-034", TacticCardDef swiftMovingStorm),
      ("fragments-of-power-035", UnitCardDef arkayneVampire),
      ("fragments-of-power-036", SupportCardDef descendantOfGods),
      ("fragments-of-power-037", TacticCardDef danceToLoec),
      ("fragments-of-power-039", QuestCardDef summonTheReserves),
      ("fragments-of-power-040", QuestCardDef weHatesThemAll),
      ("fragments-of-power-033", UnitCardDef agentOfMalekith),
      ("fragments-of-power-038", QuestCardDef snotlingInvasion),
      -- Bloodquest cycle — The Accursed Dead (pack 3)
      ("the-accursed-dead-042", LegendCardDef kurtHelborg),
      ("the-accursed-dead-044", SupportCardDef ancientVengeance),
      ("the-accursed-dead-043", UnitCardDef recklessEngineer),
      ("the-accursed-dead-057", TacticCardDef arcanePower),
      ("the-accursed-dead-045", UnitCardDef lionStandard),
      ("the-accursed-dead-051", UnitCardDef strickenWarrior),
      ("the-accursed-dead-052", SupportCardDef riftOfBattle),
      ("the-accursed-dead-053", UnitCardDef treasureThieves),
      ("the-accursed-dead-054", TacticCardDef jealousEyes),
      ("the-accursed-dead-046", TacticCardDef purgedByFlame),
      ("the-accursed-dead-049", UnitCardDef roamingShaman),
      ("the-accursed-dead-055", UnitCardDef bladesinger),
      ("the-accursed-dead-056", SupportCardDef drakenhofCastle),
      ("the-accursed-dead-058", QuestCardDef rebuildTheHold),
      ("the-accursed-dead-059", QuestCardDef hiddenOperative),
      ("the-accursed-dead-060", QuestCardDef beastmanIncursion),
      -- Bloodquest cycle — Vessel of the Winds (pack 4)
      ("vessel-of-the-winds-061", SupportCardDef windcatcherPrism),
      ("vessel-of-the-winds-062", LegendCardDef gorbadIronclaw),
      ("vessel-of-the-winds-066", UnitCardDef daImmortulz),
      ("vessel-of-the-winds-067", SupportCardDef morglorTheMangler),
      ("vessel-of-the-winds-070", UnitCardDef learnedMage),
      ("vessel-of-the-winds-074", UnitCardDef elkana),
      ("vessel-of-the-winds-075", SupportCardDef templeOfSpite),
      ("vessel-of-the-winds-072", UnitCardDef xiratp),
      ("vessel-of-the-winds-073", UnitCardDef ptarix),
      ("vessel-of-the-winds-076", UnitCardDef magePriestOfItza),
      ("vessel-of-the-winds-077", UnitCardDef clanEshinMutant),
      ("vessel-of-the-winds-063", UnitCardDef bromLongbellow),
      ("vessel-of-the-winds-064", SupportCardDef aleHall),
      ("vessel-of-the-winds-065", TacticCardDef honouringTheAncestors),
      ("vessel-of-the-winds-068", UnitCardDef masterEngineer),
      ("vessel-of-the-winds-080", QuestCardDef secretCrypts),
      ("vessel-of-the-winds-079", QuestCardDef pleasureCults),
      ("vessel-of-the-winds-078", QuestCardDef gatheringTheHorde),
      -- Bloodquest cycle — Portent of Doom (pack 5)
      ("portent-of-doom-083", UnitCardDef spiritSlayer),
      ("portent-of-doom-089", UnitCardDef princeAlthran),
      ("portent-of-doom-091", UnitCardDef fleetingShade),
      ("portent-of-doom-086", TacticCardDef progressInNumbers),
      ("portent-of-doom-087", UnitCardDef carroburgCutthroats),
      ("portent-of-doom-093", TacticCardDef murderlust),
      ("portent-of-doom-094", UnitCardDef swordsOfChaos),
      ("portent-of-doom-099", QuestCardDef unstableFlux),
      ("shield-of-the-gods-111", UnitCardDef slaaneshCultist),
      ("shield-of-the-gods-110", TacticCardDef valourOfAges),
      ("portent-of-doom-097", TacticCardDef ghostlyApparition),
      ("portent-of-doom-098", TacticCardDef shieldOfTheGods),
      ("portent-of-doom-100", QuestCardDef borderPatrol),
      -- Bloodquest cycle — Shield of the Gods (pack 6)
      ("shield-of-the-gods-101", SupportCardDef shieldOfAeons),
      ("shield-of-the-gods-103", UnitCardDef dwarfAdventurer),
      ("shield-of-the-gods-104", SupportCardDef hospitableCave),
      ("shield-of-the-gods-105", UnitCardDef manglerSquigs),
      ("shield-of-the-gods-106", SupportCardDef creaturePen),
      ("shield-of-the-gods-107", UnitCardDef steelStandard),
      ("shield-of-the-gods-109", UnitCardDef ellyrianElite),
      ("shield-of-the-gods-102", LegendCardDef anethraHelbane),
      ("shield-of-the-gods-115", SupportCardDef trinketsOfGold),
      ("shield-of-the-gods-117", SupportCardDef talismanicTatoos),
      ("shield-of-the-gods-112", TacticCardDef necrodomosProphecy),
      ("shield-of-the-gods-113", UnitCardDef blackGuards),
      ("shield-of-the-gods-114", SupportCardDef naggarondForge),
      ("shield-of-the-gods-116", TacticCardDef deathInTheShadows),
      ("shield-of-the-gods-119", QuestCardDef throughAllOfTime),
      ("shield-of-the-gods-120", QuestCardDef guardiansOfTheGods),
      -- Legends (deluxe expansion)
      ("legends-001", LegendCardDef grombrindal),
      ("legends-002", LegendCardDef thorgrimGrudgebearer),
      ("legends-003", UnitCardDef veteranSlayer),
      ("legends-005", UnitCardDef dwarfThunderer),
      ("legends-006", SupportCardDef runeOfCleaving),
      ("legends-007", TacticCardDef blastingCharge),
      ("legends-008", LegendCardDef gromThePaunch),
      ("legends-009", LegendCardDef azhagTheSlaughterer),
      ("legends-010", UnitCardDef blindRiverGoblin),
      ("legends-011", UnitCardDef redEadBoyz),
      ("legends-012", UnitCardDef frenziedBigUn),
      ("legends-015", LegendCardDef karlFranz),
      ("legends-018", UnitCardDef battleWizard),
      ("legends-020", SupportCardDef blessedHammer),
      ("legends-021", TacticCardDef callForReserves),
      ("legends-027", SupportCardDef elvenSteed),
      ("legends-028", TacticCardDef masterOfTheEarth),
      ("legends-029", LegendCardDef archaon),
      ("legends-031", UnitCardDef bloodletter),
      ("legends-032", UnitCardDef warhounds),
      ("legends-033", UnitCardDef marauderChieftain),
      ("legends-035", TacticCardDef seductiveDelusion),
      ("legends-036", LegendCardDef malekith),
      ("legends-037", LegendCardDef morathi),
      ("legends-038", UnitCardDef thiefOfEssence),
      ("legends-039", UnitCardDef darkElfAssassin),
      ("legends-040", UnitCardDef monsterOfTheDeep),
      ("legends-042", TacticCardDef bladewind),
      ("legends-043", UnitCardDef terradonRider),
      ("legends-044", UnitCardDef kroxigor),
      ("legends-045", TacticCardDef trackThePrey),
      ("legends-046", UnitCardDef stormvermin),
      ("legends-047", SupportCardDef screamingBell),
      ("legends-049", UnitCardDef shadowSentinel),
      ("legends-050", UnitCardDef wildRider),
      ("legends-052", UnitCardDef swarmOfBats),
      ("legends-053", UnitCardDef bloodDragonKnight),
      ("legends-054", SupportCardDef curseOfYears),
      -- Days of Blood (Eternal War cycle, pack 1)
      ("days-of-blood-001", LegendCardDef croneHellebron),
      ("days-of-blood-003", UnitCardDef brideOfKhaine),
      ("days-of-blood-004", SupportCardDef chillSeaWatchtower),
      ("days-of-blood-005", UnitCardDef veteranThunderers),
      ("days-of-blood-007", UnitCardDef ludwigSchwarzheim),
      ("days-of-blood-008", UnitCardDef middenheimLookout),
      ("days-of-blood-010", UnitCardDef greatFireDragon),
      ("days-of-blood-011", UnitCardDef shadowlandsHunter),
      ("days-of-blood-013", UnitCardDef iddenBoy),
      ("days-of-blood-016", UnitCardDef norseMarauders),
      ("days-of-blood-017", UnitCardDef ghorgon),
      ("days-of-blood-018", TacticCardDef recklessAttack),
      ("days-of-blood-019", SupportCardDef bordertown),
      -- Oaths of Vengeance (Eternal War cycle, pack 2)
      ("oaths-of-vengeance-021", LegendCardDef alithAnar),
      ("oaths-of-vengeance-023", SupportCardDef outlyingTower),
      ("oaths-of-vengeance-024", UnitCardDef nagarytheArcher),
      ("oaths-of-vengeance-026", TacticCardDef bandTogether),
      ("oaths-of-vengeance-027", SupportCardDef wealthOfTheHold),
      ("oaths-of-vengeance-028", UnitCardDef maidOfSigmar),
      ("oaths-of-vengeance-030", UnitCardDef wolfChariot),
      ("oaths-of-vengeance-031", UnitCardDef goblinRaiders),
      ("oaths-of-vengeance-035", UnitCardDef vaedraBloodsworn),
      ("oaths-of-vengeance-036", UnitCardDef hagGraefKnights),
      ("oaths-of-vengeance-038", UnitCardDef stealthySkink),
      ("oaths-of-vengeance-039", UnitCardDef skavenPackmaster),
      -- Battle for the Old World (Eternal War cycle, pack 3)
      ("battle-for-the-old-world-041", LegendCardDef wurrzag),
      ("battle-for-the-old-world-043", SupportCardDef mobOHutz),
      ("battle-for-the-old-world-044", UnitCardDef dedScaryBoy),
      ("battle-for-the-old-world-045", UnitCardDef ironDefenders),
      ("battle-for-the-old-world-047", UnitCardDef reiksguardElite),
      ("battle-for-the-old-world-049", SupportCardDef chapterhouseStables),
      ("battle-for-the-old-world-050", UnitCardDef lilea),
      ("battle-for-the-old-world-051", UnitCardDef nagarytheWarrior),
      ("battle-for-the-old-world-053", UnitCardDef norseClansman),
      ("battle-for-the-old-world-056", UnitCardDef slaveHunter),
      -- Glory of Days Past (Eternal War cycle, pack 4)
      ("glory-of-days-past-061", LegendCardDef thorekIronbrow),
      ("glory-of-days-past-063", UnitCardDef mineEngineers),
      ("glory-of-days-past-064", SupportCardDef karakHirnMine),
      ("glory-of-days-past-065", UnitCardDef ostlandGreatswords),
      ("glory-of-days-past-066", TacticCardDef fulminatingCage),
      ("glory-of-days-past-067", UnitCardDef masterOfQhaysh),
      ("glory-of-days-past-072", TacticCardDef getEmLadz),
      ("glory-of-days-past-073", UnitCardDef chaosDragon),
      ("glory-of-days-past-075", SupportCardDef painfulMutation),
      ("glory-of-days-past-076", UnitCardDef outlawSorcerer),
      ("glory-of-days-past-079", UnitCardDef rogueWarrior),
      ("glory-of-days-past-080", TacticCardDef strengthOfEmperors),
      ("glory-of-days-past-078", SupportCardDef markedForDeath),
      -- The Ruinous Hordes (Eternal War cycle, pack 5)
      ("the-ruinous-hordes-081", LegendCardDef sigvaldTheMagnificent),
      ("the-ruinous-hordes-082", QuestCardDef dominionOfChaos),
      ("the-ruinous-hordes-083", SupportCardDef northernWastes),
      ("the-ruinous-hordes-085", UnitCardDef steelBehemoth),
      ("the-ruinous-hordes-088", UnitCardDef kingAlrik),
      ("the-ruinous-hordes-089", UnitCardDef hornHoldDefender),
      ("the-ruinous-hordes-091", UnitCardDef avelornSojourner),
      ("the-ruinous-hordes-094", UnitCardDef wolfGobbos),
      ("the-ruinous-hordes-096", UnitCardDef coldOneChampion),
      ("the-ruinous-hordes-097", TacticCardDef testOfWill),
      ("the-ruinous-hordes-098", UnitCardDef spellweaver),
      ("the-ruinous-hordes-099", UnitCardDef restlessCorpse),
      -- Faith and Steel (Eternal War cycle, pack 6)
      ("faith-and-steel-101", LegendCardDef balthasarGelt),
      ("faith-and-steel-113", UnitCardDef skulltaker),
      ("faith-and-steel-103", SupportCardDef theEmperorsStatue),
      ("faith-and-steel-104", UnitCardDef celestialWizardAcolyte),
      ("faith-and-steel-106", UnitCardDef doomSeeker),
      ("faith-and-steel-107", TacticCardDef fearlessInBattle),
      ("faith-and-steel-111", UnitCardDef gobboBigBoss),
      ("faith-and-steel-119", SupportCardDef plunderer),
      -- Hidden Kingdoms (deluxe expansion)
      ("hidden-kingdoms-001", LegendCardDef scarLeaderKroqGar),
      ("hidden-kingdoms-003", UnitCardDef chameleonStalker),
      ("hidden-kingdoms-005", UnitCardDef saurusOldblood),
      ("hidden-kingdoms-006", SupportCardDef greatTempleOfTlazcotl),
      ("hidden-kingdoms-007", SupportCardDef sunTempleOfChotec),
      ("hidden-kingdoms-008", SupportCardDef zigguratOfQuetli),
      ("hidden-kingdoms-009", TacticCardDef ruinationOfCities),
      ("hidden-kingdoms-013", UnitCardDef shroudedWaywatcher),
      ("hidden-kingdoms-014", UnitCardDef slumberingTitan),
      ("hidden-kingdoms-015", UnitCardDef highbornChampion),
      ("hidden-kingdoms-016", SupportCardDef oakOfAges),
      ("hidden-kingdoms-018", TacticCardDef furyOfTheForest),
      ("hidden-kingdoms-019", LegendCardDef queekHeadtaker),
      ("hidden-kingdoms-021", UnitCardDef ratSwarm),
      ("hidden-kingdoms-022", UnitCardDef masterMoulder),
      ("hidden-kingdoms-024", UnitCardDef giantRats),
      ("hidden-kingdoms-029", UnitCardDef abyssalTerror),
      ("hidden-kingdoms-030", UnitCardDef lordOfTheDead),
      ("hidden-kingdoms-031", UnitCardDef darkAcolyte),
      ("hidden-kingdoms-032", UnitCardDef cacklingHexwrath),
      ("hidden-kingdoms-033", SupportCardDef mortisEngine),
      ("hidden-kingdoms-034", SupportCardDef blooddrinker),
      ("hidden-kingdoms-038", UnitCardDef shieldBearer),
      ("hidden-kingdoms-039", TacticCardDef defendYourHonor),
      ("hidden-kingdoms-040", SupportCardDef dwarfEmbassy),
      ("hidden-kingdoms-042", TacticCardDef stalemate),
      ("hidden-kingdoms-043", SupportCardDef imperialEmbassy),
      ("hidden-kingdoms-046", SupportCardDef elvenEmbassy),
      ("hidden-kingdoms-047", UnitCardDef seekerChariot),
      ("hidden-kingdoms-049", SupportCardDef daemonicOffering),
      ("hidden-kingdoms-051", TacticCardDef bloodlust),
      ("hidden-kingdoms-052", SupportCardDef bloodOffering),
      ("hidden-kingdoms-053", UnitCardDef recklessBoyz),
      ("hidden-kingdoms-054", TacticCardDef orcishArtillery),
      ("hidden-kingdoms-055", SupportCardDef shinyOffering)
    ]
